export const defi = [
  {
    name: "1inch Network",
    url: "https://1inch.io/",
    logo: "/1inchnetwork.jpeg",
    handle: "",
    description:
      "Unites decentralized protocols whose synergy enables improved operations in the DeFi space.",
  },
  {
    name: "Aave",
    url: "https://aave.com/",
    logo: "/aave.jpeg",
    handle: "",
    description: "Decentralized finance protocol that allows people to lend and borrow crypto.",
  },
  {
    name: "AlchemymixFi",
    url: "https://alchemix.fi/",
    logo: "/alchemymixfi.jpeg",
    handle: "",
    description: "Leverage a range of tokens without risk of liquidation.",
  },
  {
    name: "Aztec",
    url: "https://aztec.network/",
    logo: "/aztec.jpeg",
    handle: "",
    description: "Programmable privacy layer for web3.",
  },
  {
    name: "Balancer",
    url: "https://balancer.fi/",
    logo: "/balancer.png",
    handle: "",
    description: "",
  },
  {
    name: "Barn Bridge",
    url: "https://barnbridge.com/",
    logo: "/barnbridge.jpeg",
    handle: "",
    description: "Earn sustainable fixed income.",
  },
  {
    name: "Compound",
    url: "https://compound.finance/",
    logo: "/compound.png",
    handle: "",
    description:
      "Algorithmic, autonomous interest rate protocol built for developers to unlock a universe of open financial applications.",
  },
  {
    name: "Concentrator",
    url: "https://concentrator.aladdin.club/#/vault",
    logo: "/concentrator.jpeg",
    handle: "",
    description: "Seamless compounding made for $CRV, $CVX, and $FRAX maxis.",
  },
  {
    name: "Convex Finance",
    url: "https://www.convexfinance.com/",
    logo: "/convexfinance.jpeg",
    handle: "",
    description: "Boosts rewards for CRV stakers and liquidity providers.",
  },
  {
    name: "CoW Swap",
    url: "https://cow.fi/",
    logo: "/cowswap.jpeg",
    handle: "",
    description:
      "Finds the lowest prices from all decentralized exchanges and DEX aggregators.",
  },
  {
    name: "Curve",
    url: "https://curve.fi/#/ethereum/swap",
    logo: "/curve.jpeg",
    handle: "",
    description: "Decentralized exchange and automated market maker protocol.",
  },
  {
    name: "dYdX",
    url: "https://dydx.exchange/",
    logo: "/dydx.jpeg",
    handle: "",
    description:
      "Decentralized exchange platform that offers perpetual trading options.",
  },
  {
    name: "ElementFi",
    url: "https://www.element.fi/",
    logo: "/elementfi.jpeg",
    handle: "",
    description: "Protocol for fixed and variable yield markets.",
  },
  {
    name: "Instadapp",
    url: "https://instadapp.io/",
    logo: "/instadapp.jpeg",
    handle: "",
    description:
      "Gives all DeFi users the simplest way to access the best earning DeFi strategies.",
  },
  {
    name: "JustCryptos",
    url: "https://just.network/",
    logo: "/justcryptos.jpeg",
    handle: "",
    description:
      "Bridge that connects premium crypto currencies from the TRON network and other public chains.",
  },
  {
    name: "JustLend",
    url: "https://app.justlend.org/#/home",
    logo: "/justlend.webp",
    handle: "",
    description:
      "First official lending platform on TRON where users can borrow, lend, deposit assets and earn interests.",
  },
  {
    name: "Lido",
    url: "https://lido.fi/",
    logo: "/lido.jpeg",
    handle: "",
    description: "Use your staked assets to gain yield on top of yield.",
  },
  {
    name: "Liquity Protocol",
    url: "https://www.liquity.org/",
    logo: "/liquidityprotocall.jpeg",
    handle: "",
    description: "Interest free borrowing built on ethereum.",
  },
  {
    name: "MakerDAO",
    url: "https://makerdao.com/",
    logo: "/makerdao.jpeg",
    handle: "",
    description:
      "World's first unbiased currency and leading decentralized stablecoin.",
  },
  {
    name: "Morpho Labs",
    url: "https://www.morpho.xyz/",
    logo: "/morpholabs.jpeg",
    handle: "",
    description: "Improve your lend & borrow APY with peer-to-peer liquidity.",
  },
  {
    name: "Nested Fi",
    url: "https://nested.fi/",
    logo: "/nestedfi.jpeg",
    handle: "",
    description: "Build crypto portfolios or copy the best traders.",
  },
  {
    name: "PancakeSwap",
    url: "https://pancakeswap.finance/",
    logo: "/pancakeswap.jpeg",
    handle: "",
    description:
      "Decentralized exchange built on the BNB Chain instead of Ethereum.",
  },
  {
    name: "PortalsFi",
    url: "https://portals.fi/",
    logo: "/portalsfi.jpeg",
    handle: "",
    description: "Endpoint for swaps, transaction bundling, farming, and data.",
  },
  {
    name: "Rocket Pool",
    url: "https://rocketpool.net/#header",
    logo: "/rocketpool.jpeg",
    handle: "",
    description:
      "Liquid staking token that accrues while using an increasing exchange rate, rather than rebasing.",
  },
  {
    name: "StakeDAO",
    url: "https://stakedao.org/",
    logo: "/stakedao.jpeg",
    handle: "",
    description: "Yield. Options. Staking. Power from lockable tokens.",
  },
  {
    name: "SushiSwap",
    url: "https://www.sushi.com/",
    logo: "/sushiswap.png",
    handle: "",
    description:
      "Swap, earn, stack yields, lend, borrow, leverage all on one decentralized, community driven platform.",
  },
  {
    name: "Synthetix",
    url: "https://synthetix.io/",
    logo: "/synthetix.png",
    handle: "",
    description:
      "Allows users to mint new crypto assets that mimic both real-world assets and crypto assets.",
  },
  {
    name: "GMX",
    url: "https://gmx.io/#/",
    logo: "/gmx.jpeg",
    handle: "",
    description: "Trade BTC, ETH, AVAX and more with up to 50x leverage.",
  },
  {
    name: "Premia",
    url: "https://premia.finance/",
    logo: "/premia.jpeg",
    handle: "",
    description: "Trade BTC, ETH, AVAX and more with up to 50x leverage.",
  },
  {
    name: "Arrakis Finance",
    url: "https://www.arrakis.finance/",
    logo: "/arrakisfinance.jpeg",
    handle: "",
    description:
      "Trustless market making infrastructure & strategies on Uniswap V3.",
  },
  {
    name: "Panoptic",
    url: "https://www.panoptic.xyz/",
    logo: "/panoptic.jpeg",
    handle: "",
    description: "Perpetual, oracle-free options protocol.",
  },
  {
    name: "GammaSwap",
    url: "https://gammaswap.com/",
    logo: "/gammaswap.jpeg",
    handle: "",
    description: "Oracle Free Volatility DEX.",
  },
  {
    name: "Uniswap",
    url: "https://uniswap.org/",
    logo: "/uniswap.jpeg",
    handle: "",
    description:
      "Cryptocurrency exchange which uses a decentralized network protocol.",
  },
  {
    name: "VelodromeFi",
    url: "https://app.velodrome.finance/",
    logo: "/velodromefi.jpeg",
    handle: "",
    description: "Trading and liquidity marketplace on optimism.",
  },
  {
    name: "WBTC",
    url: "https://wbtc.network/",
    logo: "/wbtc.png",
    handle: "",
    description: "First ERC20 token backed 1:1 with Bitcoin.",
  },
  {
    name: "Yearn",
    url: "https://yearn.finance/vaults",
    logo: "/Yearn.jpeg",
    handle: "",
    description: "Yield farming platform with an intuitive interface.",
  },
  {
    name: "RWA.xyz",
    url: "RWA.xyz",
    logo: "/rwa.jpeg",
    handle: "",
    description: "Analytics and news on real world assets used in DeFi",
  },
];
