export const defi = [
  {
    name: 'Uniswap',
    url: 'https://uniswap.org/',
    logo: '/uniswap.jpeg',
    handle: "",
  },
  {
    name: 'MakerDAO',
    url: 'https://makerdao.com/',
    logo: '/makerdao.jpeg',
    handle: "",
  },
  {
    name: 'Lido',
    url: 'https://lido.fi/',
    logo: '/lido.jpeg',
    handle: "",
  },
  {
    name: 'Aave',
    url: 'https://aave.com/',
    logo: '/aave.jpeg',
    handle: "",
  },
  {
    name: 'WBTC',
    url: 'https://wbtc.network/',
    logo: '/wbtc.png',
    handle: "",
  },
  {
    name: 'Curve',
    url: 'https://curve.fi/#/ethereum/swap',
    logo: '/curve.jpeg',
    handle: "",
  },
  {
    name: '1inch Network',
    url: 'https://1inch.io/',
    logo: '/1inchnetwork.jpeg',
    handle: "",
  },
  {
    name: 'PancakeSwap',
    url: 'https://pancakeswap.finance/',
    logo: '/pancakeswap.jpeg',
    handle: "",
  },
  {
    name: 'JustLend',
    url: 'https://app.justlend.org/#/home',
    logo: '/justlend.webp',
    handle: "",
  },
  {
    name: 'CoW Swap',
    url: 'https://cow.fi/',
    logo: '/cowswap.jpeg',
    handle: "",
  },
  {
    name: 'Convex Finance',
    url: 'https://www.convexfinance.com/',
    logo: '/convexfinance.jpeg',
    handle: "",
  },
  {
    name: 'JustCryptos',
    url: 'https://just.network/',
    logo: '/justcryptos.jpeg',
    handle: "",
  },
  {
    name: 'Instadapp',
    url: 'https://instadapp.io/',
    logo: '/instadapp.jpeg',
    handle: "",
  },
  {
    name: 'Compound',
    url: 'https://compound.finance/',
    logo: '/compound.png',
    handle: "",
  },
  {
    name: 'Balancer',
    url: 'https://balancer.fi/',
    logo: '/balancer.png',
    handle: "",
  },
  {
    name: 'Rocket Pool',
    url: 'https://rocketpool.net/#header',
    logo: '/rocketpool.jpeg',
    handle: "",
  },
  {
    name: 'SushiSwap',
    url: 'https://www.sushi.com/',
    logo: '/sushiswap.png',
    handle: "",
  },
  {
    name: 'dYdX',
    url: 'https://dydx.exchange/',
    logo: '/dydx.jpeg',
    handle: "",
  },
  {
    name: 'Yearn',
    url: 'https://yearn.finance/vaults',
    logo: '/Yearn.jpeg',
    handle: "",
  },
  {
    name: 'Synthetix',
    url: 'https://synthetix.io/',
    logo: '/synthetix.png',
    handle: "",
  },
]