export const impactdaos = [
  {
    name: 'Gitcoin DAO - Grants',
    url: 'https://gitcoin.co/grants/',
    logo: '/gitcoindaogrants.jpeg',
    handle: "",
  },
  {
    name: 'Giveth',
    url: 'https://giveth.io/',
    logo: '/giveth.png',
    handle: "",
  },
  {
    name: 'KlimaDAO',
    url: 'https://www.klimadao.finance/',
    logo: '/klimadao.jpeg',
    handle: "",
  },
  {
    name: 'ESG DAO',
    url: 'https://www.esgdao.earth/',
    logo: '/esgdao.png',
    handle: "",
  },
  {
    name: 'Toucan',
    url: 'https://toucan.earth/',
    logo: '/toucan.jpeg',
    handle: "",
  },
  {
    name: 'DoinGud',
    url: 'https://doingud.com/',
    logo: '/doingud.jpeg',
    handle: "",
  },
  {
    name: 'hypercerts',
    url: 'https://hypercerts.xyz',
    logo: '/hypercerts.jpeg',
    handle: "",
  },
  {
    name: 'Panvala',
    url: 'https://www.panvala.com/',
    logo: '/panvala.jpeg',
    handle: "",
  },
  {
    name: '40ACRES',
    url: 'https://app.astrodao.com/dao/40acres.sputnik-dao.near',
    logo: '/40acres.jpeg',
    handle: "",
  },
  {
    name: 'AquaGoat',
    url: 'https://aquagoat.finance/',
    logo: '/aquagoat.jpeg',
    handle: "",
  },
  {
    name: 'Popcorn',
    url: 'https://www.popcorn.network/',
    logo: '/popcorn.jpeg',
    handle: "",
  },
  {
    name: 'CitizenDAO',
    url: 'https://citizendao.io/',
    logo: '/citizendao.jpeg',
    handle: "",
  },
  {
    name: 'Dream DAO',
    url: 'https://www.dreamdao.xyz/',
    logo: '/dreamdao.jpeg',
    handle: "",
  },
  {
    name: 'Monograma',
    url: 'https://monograma.io/home/',
    logo: '/monograma.png',
    handle: "",
  },
  {
    name: 'SeeDAO',
    url: 'https://seedao.xyz/',
    logo: '/seedao.jpeg',
    handle: "",
  },
  {
    name: 'Big Green DAO',
    url: 'https://dao.biggreen.org/',
    logo: '/biggreendao.jpeg',
    handle: "",
  },
  {
    name: 'Ed3 DAO',
    url: 'https://www.ed3dao.com/',
    logo: '/ed3dao.jpeg',
    handle: "",
  },
  {
    name: 'Future Thinkers',
    url: 'https://futurethinkers.org/village/',
    logo: '/futurethinkers.png',
    handle: "",
  },
  {
    name: 'DAOer',
    url: 'https://www.daoer.xyz/',
    logo: '/daoer.jpeg',
    handle: "",
  },
  {
    name: 'Project Ark',
    url: 'https://www.project-ark.co/',
    logo: '/projectark.jpeg',
    handle: "",
  },
  {
    name: 'Give Crypto',
    url: 'https://givecrypto.org/',
    logo: '/givecrypto.jpeg',
    handle: "",
  },
  {
    name: 'Endaoment',
    url: 'https://endaoment.org/',
    logo: '/endaoment.jpeg',
    handle: "",
  },
  {
    name: 'The Giving Block',
    url: 'https://thegivingblock.com/',
    logo: '/thegivingblock.png',
    handle: "",
  },
  {
    name: 'Daffy',
    url: 'https://www.daffy.org/',
    logo: '/daffy.png',
    handle: "",
  },
  {
    name: 'UNICEF Crypto Fund',
    url: 'https://cryptofund.unicef.io/home/',
    logo: '/unicef.jpeg',
    handle: "",
  },
  {
    name: 'On the Other Side podcast',
    url: 'https://www.othersidepod.xyz/',
    logo: '/ontheothersidepodcast.jpeg',
    handle: "",
  },
  {
    name: 'Collectively Intelligent podcast',
    url: 'https://podcasts.apple.com/podcast/collectively-intelligent/id1577798216',
    logo: '/collectivelyintelligentpodcast.png',
    handle: "",
  },
  {
    name: 'The Culture Economy podcast',
    url: 'https://anchor.fm/flex-chapman',
    logo: '/thecultureeconomypodcast.jpeg',
    handle: "",
  },
]