export const lens = [
  {
    name: "Lenster",
    url: "https://lenster.xyz/",
    logo: "/lenster.svg",
    handle: "lenster.lens",
    description:
      "Composable, decentralized, and permissionless social media web app built with Lens Protocol.",
  },
  {
    name: "Phaver",
    url: "https://phaver.com/",
    logo: "/phaver.jpeg",
    description: "Mobile first Lens UI, share-to-earn",
    handle: "phaver.lens",
  },
  {
    name: "Orb",
    url: "https://orb.ac/",
    logo: "/ORB.jpeg",
    handle: "orbapp.lens",
    description: "Lens mobile app, made for networking web3 professionals",
  },
  {
    name: "re:meme",
    url: "https://www.rememe.lol/",
    logo: "/rememe.png",
    handle: "rememe.lens",
    description: "Create and collect the best memes",
  },
  {
    name: "Lenstube",
    url: "https://lenstube.xyz/",
    logo: "/lenstube.svg",
    handle: "lenstube.lens",
    description:
      "Decentralized video-sharing platform built with Lens Protocol.",
  },
  {
    name: "Lensfrens",
    url: "https://www.lensfrens.xyz/",
    logo: "/lensgreen.jpeg",
    handle: "lensfrens.lens",
    description: "Lens profile and post UI, made by Lens Protocol team",
  },
  {
    name: "TeaParty",
    url: "https://app.teaparty.life/",
    logo: "/teaparty.jpeg",
    handle: "teaparty.lens",
    description: "Social-&-Earn (S&E) economy powered by Lens Protocol.",
  },
  {
    name: "LensPort",
    url: "https://lensport.io/",
    logo: "/lensport.png",
    handle: "lensport.lens",
    description: "Social NFT marketplace built specifically for Lens Protocol",
  },
  {
    name: "Lensta",
    url: "https://www.lensta.xyz/",
    logo: "/lensgreen.jpeg",
    handle: "",
    description: "Image feed for Lens Protocol.",
  },
  {
    name: "LensAlert",
    url: "https://lensalert.me/",
    logo: "/LensAlert.jpeg",
    handle: "",
    description: "Notification module for Lens Protocol.",
  },
  {
    name: "Buttrfly",
    url: "https://www.buttrfly.app/",
    logo: "/buttrfly.png",
    handle: "",
    description:
      "Decentralized social media app for iOS built on Lens Protocol.",
  },
  {
    name: "Lenstats",
    url: "https://lenstats.xyz/",
    logo: "/LensAnalytics.png",
    handle: "",
    description: "Web app to track data on Lens Protocol.",
  },
  {
    name: "Greenhouse",
    url: "https://greenhouse.social/",
    logo: "/Greenhouse.svg",
    handle: "greenhouse.lens",
    description: "Grow and spread your web3 roots.",
  },
  {
    name: "LensDrop",
    url: "https://lensdrop.netlify.app/",
    logo: "/lensdrop.png",
    handle: "lensdrop.lens",
    description:
      "Reward your Lens Protocol followers and fans with airdrops and special prizes.",
  },
  {
    name: "Superfun",
    url: "https://lens.superfun.social/",
    logo: "/lensgreen.jpeg",
    handle: "superfun.lens",
    description:
      "Social app for Meme artists to get rewarded for their super fun content.",
  },
  {
    name: "YUP",
    url: "https://app.yup.io/",
    logo: "/Yup.jpeg",
    handle: "yup_io.lens",
    description:
      "Follow your friends's web3 activity, curate top content from your favorite platforms.",
  },
  {
    name: "Lens Garden",
    url: "https://lensgarden.xyz/",
    logo: "/lensgreen.jpeg",
    handle: "",
    description: "Explore blooming projects of the Lens ecosystem.",
  },
  {
    name: "Dune Lens Overview",
    url: "https://dune.com/rustamov/overview",
    logo: "/dune.png",
    handle: "",
    description: "Data analytics dashboard about the Lens ecosystem",
  },
  {
    name: "PhiLand",
    url: "https://philand.xyz/",
    logo: "/philand.svg",
    handle: "philand.lens",
    description:
      "Build your personal metaverse that grows from on-chain activities.",
  },
  {
    name: "Lens Analytics",
    url: "https://www.lensanalytics.xyz/",
    logo: "/lensgreen.jpeg",
    handle: "",
    description: "Leaderboard and metrics on Lens",
  },
  {
    name: "Stats Lens",
    url: "https://stats.lens.xyz/",
    logo: "/lensgreen.jpeg",
    handle: "",
    description: "Data metrics for Lens Protocol.",
  },
  {
    name: "Sepana",
    url: "https://lens.sepana.io/",
    logo: "/lensgreen.jpeg",
    handle: "sepana.lens",
    description: "Open-source search infrastructure for the Lens protocol.",
  },
  {
    name: "Lens Token Terminal",
    url: "https://tokenterminal.com/terminal/projects/lens",
    logo: "/tokenterminal.jpeg",
    handle: "oskari.lens",
    description:
      "View several financial metrics and valuation multiples for Lens Protocol",
  },
  {
    name: "Leaderboard",
    url: "https://leaderboard.withlens.app/",
    logo: "/lensgreen.jpeg",
    handle: "",
    description: "Leaderboard of profiles on Lens Protocol.",
  },

  {
    name: "InLens",
    url: "https://inlens.xyz/",
    logo: "/inlens.svg",
    handle: "inlens.lens",
    description: "Find your friends from Twitter in Lens Protocol.",
  },
  {
    name: "Reflect",
    url: "https://reflect.withlens.app/",
    logo: "/lensgreen.jpeg",
    description: "Auto-tweet new Lens publications.",
  },
  {
    name: "Cultivator",
    url: "https://cultivator.cc/",
    logo: "/cultivator.png",
    handle: "cultivator.lens",
    description: "Explore the Lens Protocol Social Graph.",
  },
  {
    name: "Nimi",
    url: "https://nimi.eth.limo/",
    logo: "/nimi.png",
    handle: "0xnimi.eth",
    description: "Your personal web3 front page.",
  },
  {
    name: "Mashmesh",
    url: "https://social.mashmesh.knn3.xyz/",
    logo: "/Mashmesh.jpeg",
    description: "Relationship explorer to find new friends on Lens Protocol.",
  },
  {
    name: "Ooh la la",
    url: "https://www.oohlala.xyz/",
    logo: "/oohlala.png",
    description: "The web3 music player/aggregator.",
  },
  {
    name: "StemsDAO",
    url: "https://www.stemsdao.com/",
    logo: "/SteamDAO.jpeg",
    handle: "stems.lens",
    description: "Make music with your favorite artist.",
  },
  {
    name: "Soclly",
    url: "https://www.soclly.com/",
    logo: "/soclly.jpeg",
    handle: "soclly.lens",
    description:
      "Connect with a Web3 expert and be a part of the decentralized economy.",
  },
  {
    name: "Embed",
    url: "https://embed.withlens.app/",
    logo: "/lensgreen.jpeg",
    handle: "embed.lens",
    description:
      "One-click embeds for all your links posts, mirrors & comments.",
  },
  {
    name: "Mad.Finance",
    url: "https://madfinance.xyz/",
    logo: "/Madfinance.png",
    handle: "madfinance.lens",
    description:
      "Connects advertisers with creators and offers a way to monetize their content.",
  },
  {
    name: "Harfang",
    url: "https://harfang.app/",
    logo: "/harfang.png",
    handle: "harfang.lens",
    description:
      "NFT postal card creator and marketplace based on Lens Protocol.",
  },
  {
    name: "LensAI",
    url: "https://thegallerydao.vercel.app/login",
    logo: "/lensgreen.jpeg",
    handle: "artofficialintelligence.lens",
    description: "Text2Image NFT generator to monetize your AI creations.",
  },
  {
    name: "Lenscast",
    url: "https://www.raycast.com/peduarte/lenscast",
    logo: "/lenscast.jpeg",
    handle: "lenscast.lens",
    description: "Raycast Extension built with Lens Protocol.",
  },
  {
    name: "Alps Finance",
    url: "https://app.alps.finance/",
    logo: "/Alpsfinance.jpeg",
    handle: "alpsfinance.lens",
    description:
      "Decentralized social trading network to build your DeFi investing community and reputation.",
  },
  {
    name: "Garden",
    url: "https://garden.withlens.app/",
    logo: "/lensgreen.jpeg",
    handle: "",
    description:
      "Create links that only wallets following your Lens profile can click through.",
  },
  {
    name: "Meetvers",
    url: "https://app.meetvers.io/",
    logo: "/meetverse.jpeg",
    handle: "meetvers.lens",
    description: "Find friends with a similar web3 footprint.",
  },
  {
    name: "Lens Share",
    url: "https://lens-share.apoorv.xyz/",
    logo: "/lensgreen.jpeg",
    handle: "",
    description: "Post your Tweets to Lens Protocol.",
  },
];
