export const lens = [
  {
    name: "Lenster",
    url: "https://lenster.xyz/",
    logo: "/lenster.svg",
    handle: "lenster.lens",
  },
  {
    name: "Phaver",
    url: "https://phaver.com/",
    logo: "/phaver.jpeg",
    handle: "pharver.lens",
  },
  {
    name: "Orb",
    url: "https://orb.ac/",
    logo: "/ORB.jpeg",
    handle: "orbapp.lens",
  },
  {
    name: "re:meme",
    url: "https://www.rememe.lol/",
    logo: "/rememe.png",
    handle: "rememe.lens",
  },
  {
    name: "Lenstube",
    url: "https://lenstube.xyz/",
    logo: "/lenstube.svg",
    handle: "lenstube.lens",
  },
  {
    name: "Lensfrens",
    url: "https://www.lensfrens.xyz/",
    logo: "/lens.svg",
    handle: "lensfrens.lens",
  },
  {
    name: "TeaParty",
    url: "https://app.teaparty.life/",
    logo: "/teaparty.jpeg",
    handle: "teaparty.lens",
  },
  {
    name: "LensPort",
    url: "https://lensport.io/",
    logo: "/lensport.png",
    handle: "lensport.lens",
  },
  {
    name: "Lensta",
    url: "https://www.lensta.xyz/",
    logo: "/lens.svg",
    handle: "",
  },
  {
    name: "LensAlert",
    url: "https://lensalert.me/",
    logo: "/LensAlert.jpeg",
    handle: "",
  },
  {
    name: "Lenstats",
    url: "https://lenstats.xyz/",
    logo: "/LensAnalytics.png",
    handle: "",
  },
  {
    name: "Greenhouse",
    url: "https://greenhouse.social/",
    logo: "/Greenhouse.svg",
    handle: "greenhouse.lens",
  },
  {
    name: "LensDrop",
    url: "https://lensdrop.netlify.app/",
    logo: "/lensdrop.png",
    handle: "lensdrop.lens",
  },
  {
    name: "Superfun",
    url: "https://lens.superfun.social/",
    logo: "/lens.svg",
    handle: "superfun.lens",
  },
  {
    name: "YUP",
    url: "https://app.yup.io/",
    logo: "/yup.jpeg",
    handle: "yup_io.lens",
  },
  {
    name: "Lens Garden",
    url: "https://lensgarden.xyz/",
    logo: "/lens.svg",
    handle: "",
  },
  {
    name: "Dune Lens Overview",
    url: "https://dune.com/rustamov/overview",
    logo: "/dune.png",
    handle: "",
  },
  {
    name: "PhiLand",
    url: "https://philand.xyz/",
    logo: "/philand.svg",
    handle: "philand.lens",
  },
  {
    name: "Lens Analytics",
    url: "https://www.lensanalytics.xyz/",
    logo: "/lens.svg",
    handle: "",
  },
  {
    name: "Stats Lens",
    url: "https://stats.lens.xyz/",
    logo: "/lens.svg",
    handle: "",
  },
  {
    name: "Sepana",
    url: "https://lens.sepana.io/",
    logo: "/lens.svg",
    handle: "sepana.lens",
  },
  {
    name: "Lens Token Terminal",
    url: "https://tokenterminal.com/terminal/projects/lens",
    logo: "/tokenterminal.jpeg",
    handle: "oskari.lens",
  },
  {
    name: "Leaderboard",
    url: "https://leaderboard.withlens.app/",
    logo: "/lens.svg",
    handle: "",
  },
  {
    name: "Lens Share",
    url: "https://lens-share.apoorv.xyz/",
    logo: "/lens.svg",
    handle: "",
  },
  {
    name: "InLens",
    url: "https://inlens.xyz/",
    logo: "/inlens.svg",
    handle: "inlens.lens",
  },
  {
    name: "Reflect",
    url: "https://reflect.withlens.app/",
    logo: "/lens.svg",
  },
  {
    name: "Cultivator",
    url: "https://cultivator.cc/",
    logo: "/cultivator.png",
    handle: "cultivator.lens",
  },
  {
    name: "Nimi",
    url: "https://nimi.eth.limo/",
    logo: "/nimi.png",
    handle: "0xnimi.eth",
  },
  {
    name: "Mashmesh",
    url: "https://social.mashmesh.knn3.xyz/",
    logo: "/Mashmesh.jpeg",
  },
  {
    name: "Ooh la la",
    url: "https://www.oohlala.xyz/",
    logo: "/oohlala.png",
  },
  {
    name: "StemsDAO",
    url: "https://www.stemsdao.com/",
    logo: "/SteamDAO.jpeg",
    handle: "stems.lens",
  },
  {
    name: "Soclly",
    url: "https://www.soclly.com/",
    logo: "/soclly.jpeg",
    handle: "soclly.lens",
  },
  {
    name: "Embed",
    url: "https://embed.withlens.app/",
    logo: "/lens.svg",
    handle: "embed.lens",
  },
  {
    name: "Mad.Finance",
    url: "https://madfinance.xyz/",
    logo: "/Madfinance.png",
    handle: "madfinance.lens",
  },
  {
    name: "Harfang",
    url: "https://harfang.app/",
    logo: "/harfang.png",
    handle: "harfang.lens",
  },
  {
    name: "LensAI",
    url: "https://thegallerydao.vercel.app/login",
    logo: "/lens.svg",
    handle: "artofficialintelligence.lens",
  },
  {
    name: "Lenscast",
    url: "https://www.raycast.com/peduarte/lenscast",
    logo: "/lenscast.jpeg",
    handle: "lenscast.lens",
  },
  {
    name: "Alps Finance",
    url: "https://app.alps.finance/",
    logo: "/Alpsfinance.jpeg",
    handle: "alpsfinance.lens",
  },
  {
    name: "Garden",
    url: "https://garden.withlens.app/",
    logo: "/lens.svg",
    handle: "",
  },
  {
    name: "Meetvers",
    url: "https://app.meetvers.io/",
    logo: "/meetverse.jpeg",
    handle: "meetvers.lens",
  },
];
