export const music = [
  {
    name: "Sound",
    url: "https://www.sound.xyz/",
    logo: "/sound.svg",
    description:
      "Premier music NFT dropsite for artists and collectors with built in marketplace.",
  },
  {
    name: "Synthopia",
    url: "https://synthopia.io/",
    logo: "/synthopia.jpeg",
    description: "A generative music NFT experience.",
  },
  {
    name: "Beat Foundry",
    url: "https://beatfoundry.xyz/",
    logo: "/beatfoundry.svg",
    description:
      "Generative music collective and collections of on-chain music NFTs.",
  },
  {
    name: "NiftyTunes",
    url: "https://www.niftytunes.xyz/",
    logo: "/niftytunes.jpeg",
    description:
      "Lets artists distribute their music as NFTs directly from their distributor portal.",
  },
  {
    name: "Arpeggi Labs",
    url: "https://www.arpeggi.io/",
    logo: "/arpeggilabs.jpeg",
    description:
      "Music creation platform where musicians can publish their sounds for others to create with.",
  },
  {
    name: "SoundMint",
    url: "https://www.soundmint.xyz/",
    logo: "/soundmint.jpeg",
    description: "Collect a one-of-a-kind vinyl from your favorite artist.",
  },
  {
    name: "AudioGlyphs",
    url: "https://www.audioglyphs.io/",
    logo: "/audioglyphs.jpeg",
    description:
      "10,000 randomly generated, infinite audio NFTs derived from on-chain Pixelglyph data.",
  },
  {
    name: "0xSplits",
    url: "https://app.0xsplits.xyz/",
    logo: "/0xsplits.jpeg",
    description:
      "Audited, non-upgradeable set of contracts that efficiently split onchain income.",
  },
  {
    name: "Supercollector",
    url: "https://supercollector.xyz/",
    logo: "/supercollector.jpeg",
    description: "Who's collecting music NFTs.",
  },
  {
    name: "Decent",
    url: "https://decent.xyz/",
    logo: "/decent.jpeg",
    description:
      "Marketplace and infrastructure that creates NFTs collateralized by musicians' royalties.",
  },
  {
    name: "Catalog",
    url: "https://beta.catalog.works/",
    logo: "/catalog.jpeg",
    description: "NFT marketplace built specifically for the music industry.",
  },
  {
    name: "Async Art",
    url: "https://async.art/",
    logo: "/asyncart.jpeg",
    description:
      "NFT platform that enables artists to tokenize programmable digital art into layers.",
  },
  {
    name: "Zora",
    url: "https://zora.co/",
    logo: "/zora.jpeg",
    description: "Decentralized Auction Protocol for NFTs on Ethereum",
  },
  {
    name: "Audius",
    url: "https://audius.co/",
    logo: "/audius.jpeg",
    description:
      "Streaming platform built for all musicians, not just those signed to labels.",
  },
  {
    name: "Future Tape",
    url: "https://futuretape.xyz/",
    logo: "/futuretape.jpeg",
    description:
      "Experimental player for tracks on the Catalog, Sound, Nina and Zora platforms.",
  },
  {
    name: "Anotherblock",
    url: "https://anotherblock.io/",
    logo: "/anotherblock.jpeg",
    description:
      "Own a share of your favorite song – earn royalties alongside your favorite artist.",
  },
  {
    name: "Secret Garden",
    url: "https://www.secretgarden.fm/shinoda",
    logo: "/secretgarden.jpeg",
    description: "Home of the Bouquet, an interactive beat pad.",
  },
  {
    name: "EulerBeats",
    url: "https://eulerbeats.com/",
    logo: "/eulerbeats.jpeg",
    description:
      "Ultra scarce digital art and beat collection generated by applying mathematical discoveries of Euler.",
  },
  {
    name: "Zeblocks",
    url: "https://zeblocks.com/",
    logo: "/zeblocks.jpeg",
    description:
      "Blockchain enthusiasts who develop generative arts, mobile and web applications.",
  },
  {
    name: "Songcamp",
    url: "https://songcamp.mirror.xyz/",
    logo: "/songcamp.jpeg",
    description:
      "Artist network, creative studio, release club, and web3 laboratory.",
  },
  {
    name: "BeetsDAO",
    url: "https://www.beetsdao.com/",
    logo: "/beetsdao.jpeg",
    description: "Web3 collective disrupting the creator-audience connection.",
  },
  {
    name: "Phlote DAO",
    url: "https://www.phlote.co/",
    logo: "/phlotedao.png",
    description: "Introducing the best new music we find everyday, to you.",
  },
  {
    name: "Friends With Benefits",
    url: "https://www.fwb.help/",
    logo: "/friendswithbenefits.jpeg",
    description:
      "Worldwide group of cultural creators, thinkers, and builders who convene digitally and IRL to collaboratively shape web3's future.",
  },
  {
    name: "The Park",
    url: "https://thepark.coffee/",
    logo: "/thepark.jpeg",
    description: "Pioneer - revaluing music with friends.",
  },
  {
    name: "Ampl3d",
    url: "https://www.ampled.com/",
    logo: "/ampl3d.jpeg",
    description:
      "Direct support for all musicians. Collectively owned, community supported.",
  },
  {
    name: "Soneworks",
    url: "https://sone.works/",
    logo: "/soneworks.jpeg",
    description:
      "Proposal for the new digital music community and a call for participation in existing alternatives.",
  },
  {
    name: "Zoratopia",
    url: "https://www.zoratopia.world/",
    logo: "/zoratopia.jpeg",
    description:
      "Where the new internet and the culture link up - teleportion platform to your own utopia.",
  },
  {
    name: "hedsDAO",
    url: "https://heds.io/",
    logo: "/hedsdao.jpeg",
    description: "A curated audio visual community.",
  },
  {
    name: "Vuzec",
    url: "https://vuzec.com/",
    logo: "/vuzec.png",
    description: "Fans can directly support artists, and win alongside them.",
  },
  {
    name: "StemsDAO",
    url: "https://www.stemsdao.com/",
    logo: "/stemsdao.jpeg",
    description:
      "Properly rewards music creators and brings fans closer than ever to their favorite artists.",
  },
  {
    name: "0xStems",
    url: "https://0xstems.xyz/",
    logo: "/0xstems.jpeg",
    description:
      "Platform for producers, songwriters, and artists to collaborate on music projects.",
  },
  {
    name: "NiftyGateway",
    url: "https://www.niftygateway.com/",
    logo: "/niftygateway.png ",
    description:
      "Premier NFT marketplace for beginners, experts, and everyone in-between.",
  },
  {
    name: "Nina",
    url: "https://www.ninaprotocol.com/",
    logo: "/nina.png",
    description:
      "New way to publish, listen to, and purchase music - building tools for artists and fans to create their context.",
  },
  {
    name: "RELICS",
    url: "https://relics.xyz/",
    logo: "/relics.png",
    description: "The intersection of Music, Art and the Metaverse.",
  },
  {
    name: "AsyncArt",
    url: "https://async.art/",
    logo: "/asyncart.jpeg",
    description:
      "Creator platform for powerful storytelling, collaboration, and plugging into the wider ecosystem.",
  },
  {
    name: "Blockparty",
    url: "https://blockparty.co/",
    logo: "/blockparty.svg",
    description:
      "Creating the tools, communities and infrastructure for the future of music.",
  },
  {
    name: "MODA",
    url: "https://www.modadao.io/",
    logo: "/moda.jpeg",
    description:
      "Creating the tools, communities and infrastructure for the future of music.",
  },
  {
    name: "FormFunction",
    url: "https://formfunction.xyz/",
    logo: "/formfunction.jpeg",
    description:
      "Solana NFT marketplace designed for independent artists and creators.",
  },
  {
    name: "Opulous",
    url: "https://opulous.org/",
    logo: "/opulous.jpeg",
    description:
      "Mint MFTs that offer buyers a share in the revenue of a single, EP, or album.",
  },
  {
    name: "Audius",
    url: "https://audius.co/feed",
    logo: "/audiusfeed.jpeg",
    description:
      "Streaming platform built for all musicians, not just those signed to labels.",
  },
  {
    name: "Myx",
    url: "https://www.myx.audio/",
    logo: "/mix.jpeg",
    description:
      "Platform for music lovers and artists to create and stream the music they love.",
  },
  {
    name: "Emanate",
    url: "https://emanate.live/listen/spotlight",
    logo: "/emante.png",
    description:
      "Discover web3 music, collect NFTs and earn alongside your favorite artists.",
  },
  {
    name: "Serenade",
    url: "https://serenade.co/",
    logo: "/serenade.jpeg",
    description:
      "Eco-friendly destination for chart-accredited Digital Pressings.",
  },
  {
    name: "Gala Music",
    url: "https://serenade.co/",
    logo: "/galamusic.jpeg",
    description:
      "Own songs and access unique content with your favorite artists and earn rewards for listening.",
  },
  {
    name: "iamMozart",
    url: "https://cmposer-pad.webflow.io/",
    logo: "/iammozart.jpeg",
    description:
      "Own songs and access unique content with your favorite artists and earn rewards for listening.",
  },
];
