export const music = [
  {
    name: "Sound",
    url: "https://www.sound.xyz/",
    logo: "/sound.svg",
    handle: "",
  },
  {
    name: "Synthopia",
    url: "https://synthopia.io/",
    logo: "/synthopia.jpeg",
    handle: "",
  },
  {
    name: "Beat Foundry",
    url: "https://beatfoundry.xyz/",
    logo: "/beatfoundry.svg",
    handle: "",
  },
  {
    name: "NiftyTunes",
    url: "https://www.niftytunes.xyz/",
    logo: "/niftytunes.jpeg",
    handle: "",
  },
  {
    name: "Arpeggi Labs",
    url: "https://www.arpeggi.io/",
    logo: "/arpeggilabs.jpeg",
    handle: "",
  },
  {
    name: "SoundMint",
    url: "https://www.soundmint.xyz/",
    logo: "/soundmint.jpeg",
    handle: "",
  },
  {
    name: "AudioGlyphs",
    url: "https://www.audioglyphs.io/",
    logo: "/audioglyphs.jpeg",
    handle: "",
  },
  {
    name: "0xSplits",
    url: "https://app.0xsplits.xyz/",
    logo: "/0xsplits.jpeg",
    handle: "",
  },
  {
    name: "Supercollector",
    url: "https://supercollector.xyz/",
    logo: "/supercollector.jpeg",
    handle: "",
  },
  {
    name: "Decent",
    url: "https://decent.xyz/",
    logo: "/decent.jpeg",
    handle: "",
  },
  {
    name: "Catalog",
    url: "https://beta.catalog.works/",
    logo: "/catalog.jpeg",
    handle: "",
  },
  {
    name: "Async Art",
    url: "https://async.art/",
    logo: "/asyncart.jpeg",
    handle: "",
  },
  {
    name: "Zora",
    url: "https://zora.co/",
    logo: "/zora.jpeg",
    handle: "",
  },
  {
    name: "Future Tape",
    url: "https://futuretape.xyz/",
    logo: "/futuretape.jpeg",
    handle: "",
  },
  {
    name: "Anotherblock",
    url: "https://anotherblock.io/",
    logo: "/anotherblock.jpeg",
    handle: "",
  },
  {
    name: "Secret Garden",
    url: "https://www.secretgarden.fm/shinoda",
    logo: "/secretgarden.jpeg",
    handle: "",
  },
  {
    name: "EulerBeats",
    url: "https://eulerbeats.com/",
    logo: "/eulerbeats.jpeg",
    handle: "",
  },
  {
    name: "Zeblocks",
    url: "https://zeblocks.com/",
    logo: "/zeblocks.jpeg",
    handle: "",
  },
  {
    name: "Songcamp",
    url: "https://songcamp.mirror.xyz/",
    logo: "/songcamp.jpeg",
    handle: "",
  },
  {
    name: "BeetsDAO",
    url: "https://www.beetsdao.com/",
    logo: "/beetsdao.jpeg",
    handle: "",
  },
  {
    name: "Phlote DAO",
    url: "https://www.phlote.co/",
    logo: "/phlotedao.png",
    handle: "",
  },
  {
    name: "Friends With Benefits",
    url: "https://www.fwb.help/",
    logo: "/friendswithbenefits.jpeg",
    handle: "",
  },
  {
    name: "The Park",
    url: "https://thepark.coffee/",
    logo: "/thepark.jpeg",
    handle: "",
  },
  {
    name: "Ampl3d",
    url: "https://www.ampled.com/",
    logo: "/ampl3d.jpeg",
    handle: "",
  },
  {
    name: "Soneworks",
    url: "https://sone.works/",
    logo: "/soneworks.jpeg",
    handle: "",
  },
  {
    name: "Zoratopia",
    url: "https://www.zoratopia.world/",
    logo: "/zoratopia.jpeg",
    handle: "",
  },
  {
    name: "hedsDAO",
    url: "https://heds.io/",
    logo: "/hedsdao.jpeg",
    handle: "",
  },
  {
    name: "Vuzec",
    url: "https://vuzec.com/",
    logo: "/vuzec.png",
    handle: "",
  },
  {
    name: "StemsDAO",
    url: "https://www.stemsdao.com/",
    logo: "/stemsdao.jpeg",
    handle: "",
  },
  {
    name: "0xStems",
    url: "https://0xstems.xyz/",
    logo: "/0xstems.jpeg",
    handle: "",
  },
  {
    name: "NiftyGateway",
    url: "https://www.niftygateway.com/",
    logo: "/niftygateway.png ",
    handle: "",
  },
  {
    name: "Nina",
    url: "https://www.ninaprotocol.com/",
    logo: "/nina.png",
    handle: "",
  },
  {
    name: "RELICS",
    url: "https://relics.xyz/",
    logo: "/relics.png",
    handle: "",
  },
  {
    name: "AsyncArt",
    url: "https://async.art/",
    logo: "/asyncart.jpeg",
    handle: "",
  },
  {
    name: "Blockparty",
    url: "https://blockparty.co/",
    logo: "/blockparty.svg",
    handle: "",
  },
  {
    name: "MODA",
    url: "https://www.modadao.io/",
    logo: "/moda.jpeg",
    handle: "",
  },
  {
    name: "FormFunction",
    url: "https://formfunction.xyz/",
    logo: "/formfunction.jpeg",
    handle: "",
  },
  {
    name: "Opulous",
    url: "https://opulous.org/",
    logo: "/opulous.jpeg",
    handle: "",
  },
  {
    name: "Audius",
    url: "https://audius.co/feed",
    logo: "/audiusfeed.jpeg",
    handle: "",
  },
  {
    name: "Myx",
    url: "https://www.myx.audio/",
    logo: "/mix.jpeg",
    handle: "",
  },
  {
    name: "Emanate",
    url: "https://emanate.live/listen/spotlight",
    logo: "/emante.png",
    handle: "",
  },
];
