export const popular = [
  {
    name: "ENS",
    url: "https://ens.domains/",
    logo: "/ENS.svg",
    handle: "",
  },
  {
    name: "POAP",
    url: "https://poap.gallery",
    logo: "/poap.svg",
    handle: "",
  },
  {
    name: "Opensea",
    url: "https://opensea.io/",
    logo: "/opensea.svg",
    handle: "",
  },
  {
    name: "Lens",
    url: "https://lens.xyz",
    logo: "/lens.svg",
    handle: "",
  },
  {
    name: "Lenster",
    url: "https://lenster.xyz",
    logo: "/lenster.svg",
    handle: "",
  },
  {
    name: "Lenstube",
    url: "https://lenstube.xyz/",
    logo: "/lenstube.svg",
    handle: "",
  },
  {
    name: "GitPOAP",
    url: "https://gitpoap.io",
    logo: "/gitpoap.svg",
    handle: "",
  },
  {
    name: "Snapshot",
    url: "https://snapshot.org",
    logo: "/snapshot.svg",
    handle: "",
  },
  {
    name: "Proof of Humanity",
    url: "https://app.proofofhumanity.id",
    logo: "/poh.svg",
    handle: "",
  },
  {
    name: "Showtime",
    url: "https://showtime.xyz",
    logo: "/showtime.png",
    handle: "",
  },
  {
    name: "DeepDAO",
    url: "https://deepdao.io/",
    logo: "/deepdao.png",
    handle: "",
  },
  {
    name: "LooksRare",
    url: "https://101.xyz",
    logo: "/looksrare.svg",
    handle: "",
  },
  {
    name: "101.xyz",
    url: "https://101.xyz",
    logo: "/101.svg",
    handle: "",
  },
  {
    name: "Disco.xyz",
    url: "https://www.disco.xyz/",
    logo: "/disco.svg",
    handle: "",
  },
  {
    name: "Blur",
    url: "https://blur.io",
    logo: "/blur.png",
    handle: "",
  },
  {
    name: "Boardroom",
    url: "https://boardroom.io",
    logo: "/boardroom.png",
    handle: "",
  },
  {
    name: "Backdrop",
    url: "https://backdrop.so",
    logo: "/backdrop.svg",
    handle: "",
  },
  {
    name: "Farcaster",
    url: "https://www.farcaster.network/",
    logo: "/farcaster.png",
    handle: "",
  },
  {
    name: "Mazury",
    url: "https://mazury.xyz/",
    logo: "/mazury.jpg",
    handle: "",
  },
  {
    name: "Karma",
    url: "https://showkarma.xyz",
    logo: "/karma.png",
    handle: "",
  },
  {
    name: "Rarible",
    url: "https://rarible.com",
    logo: "/rarible.svg",
    handle: "",
  },
  {
    name: "Nimi",
    url: "https://nimi.eth.limo/",
    logo: "/nimi.png",
    handle: "",
  },
  {
    name: "MintKudos",
    url: "https://mintkudos.xyz/",
    logo: "/mintkudos.png",
    handle: "",
  },
  {
    name: "Orbis",
    url: "https://orbis.club",
    logo: "/orbis.png",
    handle: "",
  },
  {
    name: "Layer 3",
    url: "https://beta.layer3.xyz",
    logo: "/layer3.png",
    handle: "",
  },
  {
    name: "Oohlala",
    url: "https://www.oohlala.xyz",
    logo: "/oohlala.png",
    handle: "",
  },
  {
    name: "Galxe",
    url: "https://galxe.com",
    logo: "/galxe.svg",
    handle: "",
  },
  {
    name: "Phi",
    url: "https://philand.xyz",
    logo: "/philand.svg",
    handle: "",
  },
  {
    name: "Otterspace",
    url: "https://www.otterspace.xyz/",
    logo: "/otterspace.png",
    handle: "",
  },
];
