export const recent = [
  {
    name: "Metamask",
    url: "https://metamask.io/?utm_source=relay&utm_medium=web&utm_content=dapp_details",
    logo: "/metamask.jpeg",
    handle: "",
    description: "The world's leading web3 wallet",
  },
  {
    name: "Consensys",
    url: "https://consensys.net/?utm_source=relay&utm_medium=web&utm_content=dapp_details",
    logo: "/consensys.jpeg",
    handle: "",
    description: "Leading #thereum blockchain software company. Our products help users, developers, and financial institutions build a more trusted digital economy.",
  },
  {
    name: "EthGlobal",
    url: "https://ethglobal.com/?utm_source=relay&utm_medium=web&utm_content=dapp_details",
    logo: "/ethglobal.jpeg",
    handle: "",
    description: "Worldwide hackathons growing the Ethereum ecosystem.",
  },
  {
    name: "Zerion",
    url: "https://link3.to/zerion/?utm_source=relay&utm_medium=web&utm_content=dapp_details",
    logo: "/zerion.jpeg",
    handle: "",
    description: "Smart & Social Web3 Wallet | Explore, buidl & track your DeFi & NFT portfolios - on any chain, dApp, and wallet.",
  },
  {
    name: "Upshot",
    url: "https://upshot.xyz/?utm_source=relay&utm_medium=web&utm_content=dapp_details",
    logo: "/upshot.jpeg",
    handle: "",
    description: "Upshot provides deep insights into NFT markets and unlocks a wave of exotic new DeFi possibilities.",
  },
  {
    name: "Launch House",
    url: "https://www.launchhouse.com/?utm_source=relay&utm_medium=web&utm_content=dapp_details",
    logo: "/launchhouse.jpeg",
    handle: "",
    description: "a membership community to help ambitious founders, engineers, investors and more.",
  },
  {
    name: "Tableland",
    url: "https://tableland.xyz/?utm_source=relay&utm_medium=web&utm_content=dapp_details",
    logo: "/tableland.jpeg",
    handle: "",
    description: "Supercharge NFTs, metaverses, and games. Create dynamic web3 experiences through relational data and SQL.",
  },
  {
    name: "DeveloperDAO",
    url: "https://www.developerdao.com/?utm_source=relay&utm_medium=web&utm_content=dapp_details",
    logo: "/developerdao.jpeg",
    handle: "",
    description: "Build web3 with friends. Workshop, blog, talent board.",
  },
  {
    name: "Tessera",
    url: "https://tessera.co/?utm_source=relay&utm_medium=web&utm_content=dapp_details",
    logo: "/tessera.jpeg",
    handle: "",
    description: "The easiest way to collectively buy, own, and govern the NFTs you already know and love.",
  },
  {
    name: "Zapper",
    url: "https://zapper.fi/?utm_source=relay&utm_medium=web&utm_content=dapp_details",
    logo: "/zapper.jpeg",
    handle: "",
    description: "Explore and discover opportunities across NFTs, DAOs and DeFi.",
  },
  {
    name: "Syndicate",
    url: "https://syndicate.io/?utm_source=relay&utm_medium=web&utm_content=dapp_details",
    logo: "/syndicate.jpeg",
    handle: "",
    description: "Investing Infrastructure for Web3.",
  },
  {
    name: "thirdweb",
    url: "https://thirdweb.com/?utm_source=relay&utm_medium=web&utm_content=dapp_details",
    logo: "/thirdweb.jpeg",
    handle: "",
    description: "The complete web3 development framework.",
  },
  {
    name: "Light Wallet",
    url: "https://wallet.light.so/?utm_source=relay&utm_medium=web&utm_content=dapp_details",
    logo: "/light.jpeg",
    handle: "",
    description: "Open source wallet prototype exploring edges of crypto on mobile. One click wallet access inside iOS Safari.",
  },
  {
    name: "Fire",
    url: "https://www.joinfire.xyz/?utm_source=relay&utm_medium=web&utm_content=dapp_details",
    logo: "/fire.jpeg",
    handle: "",
    description: "The browser extension that shows a preview of what will enter and exit your wallet, before you sign.",
  },
  {
    name: "Manifold",
    url: "https://manifold.xyz/?utm_source=relay&utm_medium=web&utm_content=dapp_details",
    logo: "/manifold.jpeg",
    handle: "",
    description: "Enabling creative sovereignty in web3.",
  },
  {
    name: "LexDAO",
    url: "https://www.matchboxdao.com/?utm_source=relay&utm_medium=web&utm_content=dapp_details",
    logo: "/lexdao.jpeg",
    handle: "",
    description: "legal engineering | crypto law",
  },
  {
    name: "Loot",
    url: "https://www.lootproject.com/?utm_source=relay&utm_medium=web&utm_content=dapp_details",
    logo: "/loot.jpeg",
    handle: "",
    description: "Loot is randomized adventurer gear generated and stored on chain",
  },
  {
    name: "MatchboxDAO",
    url: "https://www.matchboxdao.com/?utm_source=relay&utm_medium=web&utm_content=dapp_details",
    logo: "/matchbox.jpeg",
    handle: "",
    description: "The ecosystem DAO to ignite and fuel fully on-chain games",
  }
];
